### ISSUE TITLE
Dock Tile Plugins category is missing in CLI output

### ISSUE THREAD

**Issue by evild3ad** [objective-see/KnockKnock#25]
The new "Dock Tile Plugins" category is missing in command line interface output. Please add it. Thank you!

**Comment by objective-see** [comment]
Thanks for the bug report. Can you expand on it a bit though? (Oh and make sure you're on the latest version 2.5.0)

Asking, as both the UI and cmdline interface simply iterate through all of the plugins ...so (in theory) there shouldn't be any discrepancy between the two. (And indeed on my box, it appears to show up/work as expected). 

And more info, much appreciated 🙏🏽

<img width="1143" alt="image" src="https://github.com/objective-see/KnockKnock/assets/11327812/3e60fd64-76b0-400d-aea3-c8ac77a55c4f">

**Comment by evild3ad** [comment]
I checked the used KnockKnock version of my incident response script and it was still v2.4.2. I copied v2.5.0 only to my "Applications" folder and NOT to the "Tools" folder of my shell script. All 19 categories are in the JSON output file 
 (including Dock Tiles Plugins). All good! :-)

I will close the issue. Thank you!
