### ISSUE TITLE
Error Msg: Getting Submissions complete, though errors were encounted (HTTP response(s): 4

### ISSUE THREAD

**Issue by Yodoma** [objective-see/KnockKnock#35]
Getting Submissions complete, though errors were encountered (HTTP response(s): 413, 413, 413, 413, 413).

macos Sequoia 15.1.1 
KnocKnock 3.0.0

<img width="602" alt="Screenshot 2024-12-05 at 9 13 51 PM" src="https://github.com/user-attachments/assets/818dbd29-1ae5-4470-9c62-cd8a88f408d8">

**Comment by objective-see** [comment]
VirusTotal has a limit on the size of files one can submit (`413: Content Too Large`)

**Comment by Yodoma** [comment]
Is there any way to solve this?

**Comment by Yodoma** [comment]
I'm not sure this is helpful  but here it is:

https://docs.virustotal.com/reference/upload-file-private-scanning
https://docs.virustotal.com/reference/files-scan
https://stackoverflow.com/questions/30282751/nodejs-upload-36mb-file-to-virustotal-failing

**Comment by objective-see** [comment]
Yes, I see, "_The VirusTotal file/scan API call is limited to 32MB._" :\ 
...so nothing we can really do from our end. 

You could likely submit the file manually via https://www.virustotal.com/gui/

**Comment by Yodoma** [comment]
KnockKnock doesn't tell me which file/files need to be submitted. How do I find out? 😀
